### ISSUE TITLE
Adding OnOrderSnapShot to WS

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-api-node-core#14]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ x] feature request

#### Brief description
The old api had onOrderSnapShot for the WS. I can't seem to find that on this version, can that be added? Is there a workaround right now? Thanks!

#### Steps to reproduce
-

##### Additional Notes:
-

**Comment by robertkowalski** [comment]
afaik the event was renamed to `ws2:auth:os`

**Comment by robertkowalski** [comment]
yes, confirmed.

example code:


```js
const ManagedOB = require('bfx-api-node-plugin-managed-ob')
const ManagedCandles = require('bfx-api-node-plugin-managed-candles')
const Watchdog = require('bfx-api-node-plugin-wd')

const { Manager } = require('bfx-api-node-core')

const m = new Manager({
  plugins: [ManagedOB(), ManagedCandles(), Watchdog({
    packetWDDelay: 30 * 1000
  })],

  transform: true,

 // set your settings here
  dms,
  apiSecret,
  apiKey,
  wsURL,
  restURL
})

m.on('ws2:auth:os', (os) => {
  console.log('hello jcbit', os)
})
```
