### ISSUE TITLE
ws2_close emits wrong socket id, manager.onWS('close') receives undefined WS value

### ISSUE THREAD

**Issue by Lecss** [bitfinexcom/bfx-api-node-core#6]
#### Issue type
- [x] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request

#### Brief description
Upon socket close being emitted, the ws_close manager event handler emits wrong socket id. 
```manager.onWS('close', ({ws}) => {})``` thus receives undefined for WS value. 

#### Steps to reproduce
- Create a new manager.
- Subscribe to open event through onWS.
- Subscribe to close event through onWS.
- Close the open socket 
```setTimeout(() => {
      ws2Manager.withSocket(socket => {
        socket.ws.close(undefined, 'Error message');
      });
    },1000)
``` 
- Check the callback args of the close event.

#### Additional Notes

- this also seems to affect notifyPlugins

**Comment by JacobPlaster** [comment]
All merged, thanks!
